#!/bin/sh

SSH_KEY=$(find ~/.ssh -name \*.pub)

unison ~/GdriveSync ssh://mob@raspberrypi/GdriveSync -sshargs="-i ${SSH_KEY%.*}"
unison ~/Videos ssh://mob@raspberrypi/Videos -sshargs="-i ${SSH_KEY%.*}"
unison ~/Music ssh://mob@raspberrypi/Music -sshargs="-i ${SSH_KEY%.*}"
